FROM python:3.10-slim

ARG app_version=0.0.0
ENV APP_VERSION=${app_version}

ENV APP_ /app
ENV PYTHONPATH /app
WORKDIR $APP_

#RUN apt-get update && apt-get install -y \
#    gcc \
#    libpq-dev

COPY service/requirements/lint.txt $APP_
RUN pip install -r lint.txt --no-cache


COPY service $APP_/service
COPY consumer $APP_/consumer
